### ISSUE TITLE
[BUG] Nothing in configuration file

### ISSUE THREAD

**Issue by Suim67** [Polymeta/PixelmonShiny#3]
When we launch the server with your mod, 

a config file "pixelmonshiny" is create yes, but he's empty.
So in game, nothing work

Do you have something that can help me please ?

**Comment by Polymeta** [comment]
What version of pixelmon are you using? What version of sponge are you using?
Can you please upload your server start up logs or look through them for potential errors?

**Comment by Suim67** [comment]
For pixelmon it is 8.1.2
sponge 1.12.2 2838-7.3.0

![image](https://user-images.githubusercontent.com/80638458/112679719-c7861f00-8e6c-11eb-9009-6cfe76f164b3.png)

When the server is online we have this on the console. And it spam a lot

**Comment by Polymeta** [comment]
Yeah, that error is expected from the configuration file missing. 

This is why I was asking for the logs that show the server and sponge (plugins) starting up. 

I haven't encountered this issue before myself, so without an error log, I can't do much. 

If you don't know what to look for in your log files, simply upload your latest.log to a gist (gist.GitHub.com) or pastebin.com

**Comment by Suim67** [comment]
[2021-03-26-7.log](https://github.com/Polymeta/PixelmonShiny/files/6213953/2021-03-26-7.log)

Okay, so this is my latest log ;p thanks for your help

**Comment by Polymeta** [comment]
You are using the wrong version of pixelmon shiny. You have the generations version where you likely need the reforged version, see releases here: https://github.com/Polymeta/PixelmonShiny/releases/tag/v1.0.1
