### ISSUE TITLE
[BUG] Menu of PixelmonShiny

### ISSUE THREAD

**Issue by Suim67** [Polymeta/PixelmonShiny#4]
Hey it's me again. 
I finaly installed the mod and its working! 

But i just discovered something : i often see pokemons of others players in the menu. 
When i tried to use the item on them it doesnt work (they dont become shiny) but the item is used and disappear.

Is that normal ? Did i miss something ? 

On this screen its the team of my friend that i see in my PixelmonShiny menu as you can see
![image](https://user-images.githubusercontent.com/80638458/112702002-6c672300-8e92-11eb-9f9d-51a5bfc1072c.png)

**Comment by Polymeta** [comment]
Okay, so just to double check some things:

- Did you give the shinyItem yourself or did someone else gave it to you?
- Can you try to be alone on your server and see if it then works correctly?
- Did you see any kind of errors or warnings in the console when the blocks get placed?

**Comment by Suim67** [comment]
I give the shinyItem by myself
When im alone on my server there is no problem and the menu is well synchronized to my team.
And no i see nothing on the console when the block is placed.

Now with another player connected, i sometime see his team in my pixelmonshiny menu. And its not always well syncronize,
if i switch two pokemons in my comp from slot 1 to 2 and from 2 to 1, its not always synchronized
and nothing again on the console

**Comment by Polymeta** [comment]
I will try to reproduce it on my local machine too, then I should be able to work out a solution to this. (If I can replicate it, that is)

**Comment by Suim67** [comment]
Okay, we found the problem.
If a player X open the ShinyItem menu at a moment t=10s he will see only his pokemons

BUT 

If a player Y open the ShinyItem menu at a moment t=15s he will see his pokemons mixed with the pokemon of the player X

and at this moment player X also will see his pokemons mixed with player Y team.

So that's not so annoying but its a fact.

**Comment by Polymeta** [comment]
Yeah got it, will try to resolve it soon. Thank you for your time! 👍

**Comment by Polymeta** [comment]
hopefully fixed with latest release, thank you for the report :)
